package com.hostelmanagement.service;

import com.hostelmanagement.entity.*;
import com.hostelmanagement.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class HostelService {
 private final FloorRepository floors; private final RoomRepository rooms; private final BedRepository beds; private final ResidentRepository residents; private final RentRecordRepository rent;
 public HostelService(FloorRepository floors,RoomRepository rooms,BedRepository beds,ResidentRepository residents,RentRecordRepository rent){this.floors=floors;this.rooms=rooms;this.beds=beds;this.residents=residents;this.rent=rent;}
 public List<Floor> floors(){return floors.findAll();} public Floor floor(Long id){return floors.findById(id).orElseThrow(()->new NoSuchElementException("Floor not found"));}
 public Floor saveFloor(Floor value){return floors.save(value);} public void deleteFloor(Long id){if(!rooms.findByFloorId(id).isEmpty()) throw new IllegalStateException("Floor has rooms"); floors.deleteById(id);}
 public List<Room> rooms(){return rooms.findAll();} public List<Room> rooms(Long floorId){return rooms.findByFloorId(floorId);} public Room room(Long id){return rooms.findById(id).orElseThrow(()->new NoSuchElementException("Room not found"));}
 public Room saveRoom(Room value,Long floorId){value.setFloor(floor(floorId)); return rooms.save(value);} public void deleteRoom(Long id){if(beds.findByRoomId(id).stream().anyMatch(b->b.getStatus()==BedStatus.OCCUPIED)) throw new IllegalStateException("Room has active residents"); rooms.deleteById(id);}
 public List<Bed> beds(Long roomId){return beds.findByRoomId(roomId);} @Transactional public Bed addBed(Long roomId,Integer number){Room room=room(roomId); Bed bed=beds.save(new Bed(number,room)); refreshRoom(room); return bed;}
 public List<Resident> residents(String search){return search==null||search.trim().isEmpty()?residents.findAll():residents.findByFullNameContainingIgnoreCaseOrPhoneContaining(search,search);}
 public Resident resident(Long id){return residents.findById(id).orElseThrow(()->new NoSuchElementException("Resident not found"));} public Resident saveResident(Resident r){return residents.save(r);}
 @Transactional public Resident allocate(Long residentId,Long bedId){Resident r=resident(residentId); Bed b=beds.findById(bedId).orElseThrow(()->new NoSuchElementException("Bed not found")); if(b.getStatus()!=BedStatus.AVAILABLE||b.getResident()!=null) throw new IllegalStateException("Bed is already occupied"); if(residents.findAll().stream().anyMatch(x->x.getStatus()==ResidentStatus.ACTIVE&&x.getBed()!=null&&x.getId().equals(residentId))) throw new IllegalStateException("Resident already has an active allocation"); r.setBed(b); r.setStatus(ResidentStatus.ACTIVE); b.setStatus(BedStatus.OCCUPIED); residents.save(r); beds.save(b); refreshRoom(b.getRoom()); return r; }
 @Transactional public Resident vacate(Long id){Resident r=resident(id); if(r.getBed()!=null){Bed b=r.getBed(); b.setStatus(BedStatus.AVAILABLE); b.setResident(null); beds.save(b); refreshRoom(b.getRoom()); r.setBed(null);} r.setStatus(ResidentStatus.VACATED); return residents.save(r);}
 public List<RentRecord> rent(String month){return month==null?rent.findAll():rent.findByBillingMonth(month);} @Transactional public RentRecord payment(RentRecord record,Long residentId){Resident r=resident(residentId); record.setResident(r); int paid=record.getAmountPaid()==null?0:record.getAmountPaid(); if(paid>record.getRentAmount()) throw new IllegalArgumentException("Payment exceeds outstanding rent"); record.setStatus(paid==0?PaymentStatus.PENDING:paid<record.getRentAmount()?PaymentStatus.PARTIALLY_PAID:PaymentStatus.PAID); if(paid>0)record.setPaymentDate(LocalDate.now()); return rent.save(record);}
 public Map<String,Object> dashboard(){List<Room> allRooms=rooms.findAll(); List<Bed> allBeds=beds.findAll(); List<Resident> allResidents=residents.findAll(); String month=YearMonth.now().toString(); List<RentRecord> current=rent.findByBillingMonth(month); int expected=current.stream().mapToInt(RentRecord::getRentAmount).sum(); int collected=current.stream().mapToInt(x->x.getAmountPaid()==null?0:x.getAmountPaid()).sum(); Map<String,Object> data=new LinkedHashMap<>(); data.put("totalFloors",floors.count());data.put("totalRooms",allRooms.size());data.put("totalBeds",allBeds.size());data.put("occupiedBeds",allBeds.stream().filter(x->x.getStatus()==BedStatus.OCCUPIED).count());data.put("availableBeds",allBeds.stream().filter(x->x.getStatus()==BedStatus.AVAILABLE).count());data.put("totalResidents",allResidents.stream().filter(x->x.getStatus()!=ResidentStatus.VACATED).count());data.put("rentExpected",expected);data.put("rentCollected",collected);data.put("pendingRent",Math.max(0,expected-collected));data.put("vacantRooms",allRooms.stream().filter(x->x.getStatus()==RoomStatus.AVAILABLE).count());data.put("partiallyOccupiedRooms",allRooms.stream().filter(x->x.getStatus()==RoomStatus.PARTIALLY_OCCUPIED).count());data.put("fullyOccupiedRooms",allRooms.stream().filter(x->x.getStatus()==RoomStatus.FULLY_OCCUPIED).count());data.put("occupancy",allRooms.stream().map(x->Collections.singletonMap("room",x.getRoomNumber())).collect(Collectors.toList())); return data;}
 private void refreshRoom(Room room){List<Bed> list=beds.findByRoomId(room.getId()); long occupied=list.stream().filter(x->x.getStatus()==BedStatus.OCCUPIED).count(); if(room.getStatus()==RoomStatus.MAINTENANCE)return; room.setStatus(occupied==0?RoomStatus.AVAILABLE:occupied==list.size()?RoomStatus.FULLY_OCCUPIED:RoomStatus.PARTIALLY_OCCUPIED); rooms.save(room);}
}
