package com.hostelmanagement.controller;

import com.hostelmanagement.entity.*; import com.hostelmanagement.service.HostelService;
import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api")
public class HostelController { private final HostelService service; public HostelController(HostelService service){this.service=service;}
 @GetMapping("/floors") public List<Floor> floors(){return service.floors();} @GetMapping("/floors/{id}") public Floor floor(@PathVariable Long id){return service.floor(id);} @PostMapping("/floors") public ResponseEntity<Floor> addFloor(@RequestBody Floor f){return ResponseEntity.status(HttpStatus.CREATED).body(service.saveFloor(f));} @PutMapping("/floors/{id}") public Floor editFloor(@PathVariable Long id,@RequestBody Floor f){f.setId(id);return service.saveFloor(f);} @DeleteMapping("/floors/{id}") public void deleteFloor(@PathVariable Long id){service.deleteFloor(id);}
 @GetMapping("/rooms") public List<Room> rooms(@RequestParam(required=false) Long floorId){return floorId==null?service.rooms():service.rooms(floorId);} @GetMapping("/rooms/{id}") public Room room(@PathVariable Long id){return service.room(id);} @PostMapping("/rooms") public ResponseEntity<Room> addRoom(@RequestBody Map<String,Object> body){Room r=new Room((String)body.get("roomNumber"),null,Integer.valueOf(body.get("numberOfBeds").toString()),Integer.valueOf(body.get("monthlyRent").toString()),Integer.valueOf(body.getOrDefault("securityDeposit",0).toString()),(String)body.getOrDefault("roomType","Custom"),(String)body.getOrDefault("description",""));return ResponseEntity.status(HttpStatus.CREATED).body(service.saveRoom(r,Long.valueOf(body.get("floorId").toString())));} @DeleteMapping("/rooms/{id}") public void deleteRoom(@PathVariable Long id){service.deleteRoom(id);}
 @GetMapping("/rooms/{roomId}/beds") public List<Bed> beds(@PathVariable Long roomId){return service.beds(roomId);} @PostMapping("/rooms/{roomId}/beds") public Bed addBed(@PathVariable Long roomId,@RequestBody Map<String,Integer> body){return service.addBed(roomId,body.get("bedNumber"));}
 @GetMapping("/residents") public List<Resident> residents(@RequestParam(required=false) String search){return service.residents(search);} @GetMapping("/residents/{id}") public Resident resident(@PathVariable Long id){return service.resident(id);} @PostMapping("/residents") public ResponseEntity<Resident> addResident(@RequestBody Resident r){return ResponseEntity.status(HttpStatus.CREATED).body(service.saveResident(r));} @PutMapping("/residents/{id}") public Resident editResident(@PathVariable Long id,@RequestBody Resident r){r.setId(id);return service.saveResident(r);} @PostMapping("/allocations") public Resident allocate(@RequestParam Long residentId,@RequestParam Long bedId){return service.allocate(residentId,bedId);} @PostMapping("/allocations/{id}/vacate") public Resident vacate(@PathVariable Long id){return service.vacate(id);}
 @GetMapping("/payments") public List<RentRecord> payments(@RequestParam(required=false) String month){return service.rent(month);} @PostMapping("/payments") public ResponseEntity<RentRecord> payment(@RequestBody RentRecord r,@RequestParam Long residentId){return ResponseEntity.status(HttpStatus.CREATED).body(service.payment(r,residentId));}
 @GetMapping("/dashboard/summary") public Map<String,Object> dashboard(){return service.dashboard();} @GetMapping("/dashboard/occupancy") public Map<String,Object> occupancy(){return service.dashboard();} @GetMapping("/dashboard/rent-summary") public Map<String,Object> rentSummary(){return service.dashboard();}
}
